kind: List
apiVersion: v1
items:
- kind: Pod
  apiVersion: v1
  metadata:
    labels:
      name: server
    name: server
  spec:
    containers:
    - name: c
      image: quay.io/mangirdas/go-test-app
      command:
       - "/usr/local/bin/http"
       - "8081"
      ports:
       - containerPort: 8081
    - name: s
      image: quay.io/mangirdas/go-test-app
      command:
       - "/usr/local/bin/http"
       - "8080"
      ports:
       - containerPort: 8080
- kind: Service
  apiVersion: v1
  metadata:
    name: server
  spec:
    selector:
      name: server
    ports:
    - port: 8080
